apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
spec:
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceRepos:
  - "*"